### ISSUE TITLE
Is this julia  1.0 Material?

### ISSUE THREAD

**Issue by datnamer** [andyferris/Traitor.jl#5]
Should we plan on our code moving to a trait based kind system anytime soon?

**Comment by andyferris** [comment]
Personally, I think it might be too early to tell if this is the "future".  After all, one of the main purposes of this package is to experiment with these ideas and see how they play out in real code.

However, I do think Julia's current multiple-dispatch scheme is quite powerful, and we can already do some quite amazing things with it without too much effort. It becomes slightly harder when you want to dispatch on multiple properties of an object, which is where _Traitor_ can help. I imagine in the future we'll be able to use traits to help out in those situations, rather than totally move the entire Julia code-base to a multiple-inheritance trait-based dispatch. 

I could imagine 1.0 _might_ use the same syntax to express traits as here, without needing the `@traitor` macro.

**Comment by timholy** [comment]
At the risk of sounding too Zen, "the only way to know the future is to make it happen." I mean that seriously: I can't even predict how I'll spend my own time, let alone what other people will choose to do. When it comes to guessing how development will proceed, my own personal crystal ball's batting average would not be worth the digital baseball card it's not printed on.

**Comment by c42f** [comment]
Haha, doesn't sound too Zen to me Tim, sounds like practical advice!

@datnamer to give you some certainty - from my impression a fully general traits-based dispatch system is _extremely_ unlikely to be the main way to do dispatch in julia 1.0.  Traitor is simply a playground for ideas and syntax at this stage, about half of which Andy and I wrote on the (long) plane trip back from juliacon ;-)

IMHO the aim of this package should be to see what _minimal_ syntax and runtime support would be required in julia-1.0 to allow people to experiment with various trait implementations.

**Comment by datnamer** [comment]
Thanks for the thoughts everyone!
